name: nemo_neva
engine_dir: ./neva
input_media: ./test.jpg
input_text: "Hi! What is in this image?"
batch_size: 1
infer:
  top_k: 1  # The number of highest probability vocabulary tokens to keep for top-k-filtering.
  top_p: 0.0 # If set to float < 1, only the most probable tokens with probabilities that add up to top_p or higher are kept for generation.
  temperature: 1.0 # sampling temperature
  repetition_penalty: 1.0  # The parameter for repetition penalty. 1.0 means no penalty.
  num_beams: 1
  max_new_tokens: 30
  lora_uids: null
