name: "NeMo Code release"

on:
  workflow_dispatch:
    inputs:
      branch: 
        description: Branch to release
        required: true
        type: string
jobs: 
  main:
    if: contains(fromJSON('["ko3n1g"]'), github.actor)
    runs-on: ubuntu-latest
    environment: 
      name: main
    steps:  

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
          ref: ${{ inputs.branch }}

      - name: Create release
        id: version-number
        run: |
          cd ${{ github.run_id }}
          VERSION=$(python -c "import nemo; print(nemo.__version__)")
          
          NAME="NVIDIA Neural Modules ${VERSION}"
          CHANGELOG=$(awk '/^## '"$NAME"'/{flag=1; next} /^## /{flag=0} flag' CHANGELOG.md)
          CHANGELOG=$(echo "$CHANGELOG" | sed '/./,$!d' | sed ':a;N;$!ba;s/\n$//')

          PAYLOAD=$(jq \
                      -n \
                      -c \
                      --arg TAG_NAME "v${VERSION}" \
                      --arg CI_COMMIT_BRANCH "${{ inputs.branch }}" \
                      --arg NAME "$NAME" \
                      --arg BODY "$CHANGELOG" \
                      '{
                        "tag_name": $TAG_NAME,
                        "target_commitish": $CI_COMMIT_BRANCH,
                        "name": $NAME,
                        "body": $BODY,
                        "draft": false,
                        "prerelease": false,
                        "generate_release_notes": false
                      }'
                  )

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NVIDIA/NeMo/releases \
            -d "$PAYLOAD"
      
      - name: Build, test, and release wheel
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          cd ${{ github.run_id }}
          EXPECTED_VERSION=$(python -c 'import nemo; print(nemo.__version__)')

          python3 -m pip install --upgrade build
          python3 -m build

          pip install dist/*.whl

          cd ../

          INSTALLED_VERSION=$(python -c 'import nemo; print(nemo.__version__)')
          
          if [[ "$INSTALLED_VERSION" != "$EXPECTED_VERSION" ]]; then
            echo 'Wheel has an outdated version, mission abort immediately!'
            exit 1
          fi

          echo Proceed with uploading wheel...
          cd ${{ github.run_id }}
          python3 -m pip install --upgrade twine
          python3 -m twine upload --repository pypi dist/*

      - name: notify
        run: |
          VERSION=${{ steps.version-number.outputs.VERSION }}

          URL="https://github.com/NVIDIA/NeMo/releases/tag/v$VERSION"
          MESSAGE='{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Releasebot 🤖: NeMo-Toolkit released <'$URL'|`'$VERSION'`> 🚀"
                }
              }
            ]
          }'


          curl -X POST -H "Content-type: application/json" --data "$MESSAGE" ${{ secrets.SLACK_RELEASE_ENDPOINT }}